export const ARTICLE_VISIBLE = 'ARTICLE_VISIBLE';
export const ARTICLE_TIME_OUT = 'ARTICLE_TIME_OUT';
export const COMPONENT_TIME_OUT = 'COMPONENT_TIME_OUT';
export const ARTICLE_LOADING = 'ARTICLE_LOADING';
export const ARTICLE_ACTIVE = 'ARTICLE_ACTIVE';